### ISSUE TITLE
Docker SSH $PATH incomplete

### ISSUE THREAD

**Issue by I-am-Future** [tonyyxliu/CUHKSZ-CSC4005#10]
Hi, 
    I found a problem installing the docker, and now I successfully solve it by myself. Here's the details:

**What I did:**
Follow `docker_installation_guide.md`, successfully established docker container and ssh.
Compile (some of) sample programs successfully on the docker's direct terminal. (by `docker exec -it <CONTAINER ID> bash` command) (For some in it, I think there are environment problems. Let's talk it in today night tutorial)

**What goes wrong:**
I can compile program by `pgc++` and `nvc++` well in the direct terminal, but I failed by ssh connection's terminal: 

> [root@b6c4864d9ad7 ~]# pgc++
-bash: pgc++: command not found

**What I found:**
In the local terminal, when I type `echo $PATH`, result is:

> echo $PATH
/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/clusterkit/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/tests/imb:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/hcoll/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ucx/mt/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/extras/qd/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/nvshmem/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/nccl/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/profilers/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

But in ssh's terminal, the result of `echo $PATH` is only:

> /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

I located that pgc++ and other compilers are at “/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/”, which is not in the "$PATH"

Therefore, I recommend that when in the installation, it's better to add this line:

```sh
echo 'export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/:$PATH' >> ~/.bashrc
source ~/.bashrc
```

By doing this, I solved this problem, I can run `pgc++` etc. in the ssh's terminal. 

**Update:**

Since the $PATH in ssh connection is far smaller than $PATH locally, many other path missed, for example, `mpirun`. 

In some degree, I think it's good to directly add all of the $PATH locally to the .bashrc. 

<!--```
# in ~/.bashrc
export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin/:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/clusterkit/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/tests/imb:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/hcoll/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ucx/mt/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/extras/qd/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/compilers/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/nvshmem/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/nccl/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/profilers/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```-->

Many thanks to your work!

Thank you!

**Comment by tonyyxliu** [comment]
Hi @I-am-Future 

Thank you for pointing this out. Actually, I have included this in the instruction before, and you may refered to the older version of this instruction. Anyway, it is important to notice the student to always refer to the latest version of all the instruction documentations on GitHub.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/62693471/ef41e04b-0118-436f-b3be-0ab2fb193d42)

**Comment by tonyyxliu** [comment]
Thank you for pointing this out! I used to focus on the CUDA path only. Maybe we can compile `pgc++` without explicitly assigning the version of CUDA by importing the compiler path of nvhpc to $PATH.

**Comment by I-am-Future** [comment]
Yes, that's the problem, $PATH in ssh connection is inconsistent with the terminal opend locally. I found further problem that even I added mpic++/mpirun command in the $PATH, ssh's terminal compilation still not work. It cannot locate the libs:

> [root@b6c4864d9ad7 sample_programs]# mpic++ ./mpi_hello.cpp -o mpi_hello
/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/bin/.bin/mpic++: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory

This .so file is at here, `/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/lib/libopen-rte.so.40`, which is not in the $PATH. 

I guess, some other environment variable are inherit (`$LD_LIBRARY_PATH`) in the docker, indicating the linking library position. but not in ssh. (Indeed, I found no $LD_LIBRARY_PATH in the ssh terminal. But only at local terminal)

**Comment by I-am-Future** [comment]
> Yes, that's the problem, $PATH in ssh connection is inconsistent with the terminal opend locally. I found further problem that even I added mpic++/mpirun command in the $PATH, ssh's terminal compilation still not work. It cannot locate the libs:
> 
> > [root@b6c4864d9ad7 sample_programs]# mpic++ ./mpi_hello.cpp -o mpi_hello
> > /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/bin/.bin/mpic++: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
> 
> This .so file is at here, `/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/comm_libs/hpcx/hpcx-2.8.1/ompi/lib/libopen-rte.so.40`, which is not in the $PATH.
> 
> I guess, some other environment variable are inherit (`$LD_LIBRARY_PATH`) in the docker, indicating the linking library position. but not in ssh. (Indeed, I found no $LD_LIBRARY_PATH in the ssh terminal. But only at local terminal)

So here's my solution to the all problem: in the local terminal (start by `docker exec` or in the docker desktop app, run the following command: 

```sh
echo export 'LD_LIBRARY_PATH'=`echo $LD_LIBRARY_PATH`:'$LD_LIBRARY_PATH' >> ~/.bashrc
echo export 'PATH'=`echo $PATH`:'$PATH' >> ~/.bashrc

source ~/.bashrc

# check if there are a long string:
echo $PATH
echo $LD_LIBRARY_PATH
```

Seems, at least by doing this, the problem can be solved. I'll do a pull-request.
