### ISSUE TITLE
Problem: After compilation and running, the program reports "Illegal instruction"

### ISSUE THREAD

**Issue by moonight3547** [tonyyxliu/CUHKSZ-CSC4005#12]
I meet the problem https://github.com/tonyyxliu/CSC4005-2023Fall/issues/4 first, and then I tried the suggestion provided by TA and installed the C/C++ of version 7.3.1 instead of 4.8.5. 

After that, I can compile the program avx512_vectorized_addition.cpp. But after I running it, it reports "Illegal instruction" instead of the regular output. 
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89500732/661bfaf5-f5a0-4f6d-98d6-78ff09b1ea37)

Does anyone know how to solve this problem?

**Comment by moonight3547** [comment]
By the way, I met this problem in the docker on my machine, not the cluster.

**Comment by moonight3547** [comment]
The program works if I change all those "_mm512" into "_mm256". But I'm still wondering why "_mm512" doesn't work. 

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89500732/7b99b164-5af9-426e-b50d-f29c28d16bfb)

**Comment by tonyyxliu** [comment]
Maybe you need to execute `lscpu` on your docker to check if your CPU supports AVX-512 instruction set. From the error message, I guess it does not. Changing _mm512 to _mm256 works means that your CPU supports AVX-256 only (denoted as AVX2).

**Comment by moonight3547** [comment]
The problem is that I can find avx512f in the flags.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89500732/986c3026-4670-46af-9489-6e48afc61a5a)


> Maybe you need to execute `lscpu` on your docker to check if your CPU supports AVX-512 instruction set. From the error message, I guess it does not. Changing _mm512 to _mm256 works means that your CPU supports AVX-256 only (denoted as AVX2).

**Comment by tonyyxliu** [comment]
Hi, @moonight3547 
Would you please upload the compilation command using `clang++` here, like what we have discussed during the office hour? That may help others to solve their problem. Thank you!

**Comment by tonyyxliu** [comment]
The solution is to directly compile and execute the avx-512 program on host MacOS system with `clang++` instead of in the docker container.

**Comment by moonight3547** [comment]
For MacOS machines with intel chip that support avx512f, you can try the following command to compile the avx512 program on the host system, instead of in the docker. 

I succeeded with the command
`clang++ -mavx512f avx512_vectorized_addition.cpp -o avx512_vectorized_addition -std=c++11`
