### ISSUE TITLE
nvcc-Error-CUDA version 10.2 was not installed with this HPC SDK: /opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/10.2/bin

### ISSUE THREAD

**Issue by GuanlinWU123** [tonyyxliu/CUHKSZ-CSC4005#13]
Hi! When I follow the guide of docker installation. I found the "nvcc --version" outputs the incorrect information. I'm wondering how to solve this problem?
![Screenshot from 2023-09-19 14-09-58](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/76504335/5942205c-5824-4556-962f-bae83297686a)

**Comment by hey-money** [comment]
I encountered the same issue. Would you describe the solution briefly? Thank you.

**Comment by hey-money** [comment]
The following commands solve the issue on my laptop:
`echo "export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin:$PATH" >> ~/.bashrc`
`echo "export CUDA_TOOLKIT_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4" >> ~/.bashrc`
