### ISSUE TITLE
May I just change the docker image location just by modifying the set

### ISSUE THREAD

**Issue by SummerSunnyNight** [tonyyxliu/CUHKSZ-CSC4005#14]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/7ca20d7d-1db7-4200-9a6c-5a7cc2b78d53)
↑Like this, rather than following the instruction of TA(Many thanks for TA efforts).

**Comment by tonyyxliu** [comment]
Hi @SummerSunnyNight 

According to the official documentation provided by Docker, you can change the location where docker images are stored by the **Resource** setting in your screenshot, if the Hyper-V mode is on.

https://docs.docker.com/desktop/settings/windows/#resources

**Comment by SummerSunnyNight** [comment]
> Hi @SummerSunnyNight
> 
> According to the official documentation provided by Docker, you can change the location where docker images are stored by the **Resource** setting in your screenshot, if the Hyper-V mode is on.
> 
> https://docs.docker.com/desktop/settings/windows/#resources

It is weird since I checked that my system is windows 10 home, with no hyper-v func, however the image storage location is still successfully changed to the place I selected _E:\....._
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/b626e4bd-f337-4887-b613-c5fc1ab12173)

**Comment by tonyyxliu** [comment]
I am not sure about the details, but if the disk images are stored at the location specified by you, and docker commands execute without problem, then it is great.

I will consider adding this method of changing docker image location to our docs. Thank you for introducing it to me!

**Comment by xhn2333** [comment]
Please don't directly move the virtual disk file. Docker on Windows is based on WSL2 and this disk file is for WSL2 (but not docker image files). If you move or delete this file, WSL2 may be not able to find the file, which will contribute to the failed to start WSL2 service.
