### ISSUE TITLE
"libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown" when creating the new container

### ISSUE THREAD

**Issue by t0rit0** [tonyyxliu/CUHKSZ-CSC4005#15]
For some reason I need to rebuild the container and when I run the command `docker run -it -d -p 2222:22 --gpus all --name csc4005 <IMAGE ID>`, I meet the error shown as below:

> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
> nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

My computer is __win10__ operating system and has an NVIDIA graphics card. The detailed information of `nvidia-smi` shown as below
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.42                 Driver Version: 537.42       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   58C    P8               6W /  80W |    524MiB /  6144MiB |     32%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
After I tried to reinstall the docker and update the NVIDIA driver the problem remains.

Thank you very much if anyone can help.

**Comment by t0rit0** [comment]
The image is from the command `docker pull nvcr.io/nvidia/nvhpc:21.7-devel-cuda11.4-centos7`

**Comment by tonyyxliu** [comment]
Hi torit0,

I have searched on the internet, but did not find a satisfactory solution for your problem.

From the error message, it seems that the shared object cannot be found on your computer, so I suppose it is due to the Windows system path. The following two are the system paths that I set on my Windows computer, just for your reference. Please have a check where the NVIDIA driver is installed in your computer, and have a try by setting the system path to see if it is works.

```bash
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
```

**Comment by t0rit0** [comment]
I checked the `PATH` in the system variable and found these two paths in the `PATH` list. Then I also tried to add them into the `PATH` from the user variable. After I reboot my computer the problem remains. 

But still thanks for your help

**Comment by t0rit0** [comment]
The problem is solved after I reinstall the NVIDIA driver and the docker desktop. Thanks!
