### ISSUE TITLE
Problem arise when running "docker run -it -d -p 2222:22 --gpus all --name csc4005 2306fd2cb44f"

### ISSUE THREAD

**Issue by SummerSunnyNight** [tonyyxliu/CUHKSZ-CSC4005#16]
GPU info:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/c9adab9b-3c7d-4a98-9719-cfd9ed5064e2)
Screenshot of the error：
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/d73f695d-32af-4a06-ae3d-8503b4c5bb4c)
and there is no container running↓:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/bbf386af-3845-4885-a6ac-1fe8e5278705)
I follow the instruction given by _https://github.com/tonyyxliu/CSC4005-2023Fall/blob/main/docs/docker_installation_guide.md_  step by step.
Hope someone can help me, Thanks.

**Comment by SummerSunnyNight** [comment]
The docker images repository is also different from the one in the instruction:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/e030774c-f584-4d88-b6b6-86027251114c)

**Comment by tonyyxliu** [comment]
> The docker images repository is also different from the one in the instruction: ![image](https://user-images.githubusercontent.com/73238595/270145138-e030774c-f584-4d88-b6b6-86027251114c.png)

I think this is because you load the docker image by downloading it from the cluster instead of using docker pull.

**Comment by SummerSunnyNight** [comment]
> > The docker images repository is also different from the one in the instruction: ![image](https://user-images.githubusercontent.com/73238595/270145138-e030774c-f584-4d88-b6b6-86027251114c.png)
> 
> I think this is because you load the docker image by downloading it from the cluster instead of using docker pull.

So does it mean i should try again by using the pull instruction? But actually the load instruction of mine goes smoothly without error. The main problem for me here is the "run" instruction:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/9566ebcc-e3c2-4ab3-9ee9-2a13fe5f63c7)
Still many thanks, I will try again by pull and bring back the feedback later.

**Comment by SummerSunnyNight** [comment]
> > The docker images repository is also different from the one in the instruction: ![image](https://user-images.githubusercontent.com/73238595/270145138-e030774c-f584-4d88-b6b6-86027251114c.png)
> 
> I think this is because you load the docker image by downloading it from the cluster instead of using docker pull.

Problem finally solved by updating my windows system to 22h2.
Corresponding blog here:_https://blog.csdn.net/rocking_struggling/article/details/126068555_
Thanks for TA attention. Hope this thread can help more people hhhh.
