### ISSUE TITLE
Cannot do "yum install cmake3 -y" in my docker

### ISSUE THREAD

**Issue by maryhadalittlecode** [tonyyxliu/CUHKSZ-CSC4005#18]
When I ran "yum install cmake3 -y", I got an error 

`Loading mirror speeds from cached hostfile
 * base: mirrors.jlu.edu.cn
 * centos-sclo-rh: mirrors.jlu.edu.cn
 * centos-sclo-sclo: mirror.lzu.edu.cn
 * extras: mirror.lzu.edu.cn
 * updates: mirror.lzu.edu.cn
No package cmake3 available.`

Thanks for any help!

**Comment by tonyyxliu** [comment]
Hi @MARYscu 

Could you please try to install the `epel-release` package first and see if you find the `cmake3` package then?

`yum install -y epel-release`
, then execute
`yum install -y cmake3`

**Comment by kouzitadokorro** [comment]
I have tried to follow these instructions, however I find that the cmake version has not been updated.
![1](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/144871516/97f323df-1ada-40f0-bcac-0672908d4e09)

**Comment by tonyyxliu** [comment]
Use cmake3 —version instead of cmake —version, and you will get the latest cmake.

**Comment by tonyyxliu** [comment]
You should also use `cmake3 ..` to build cmake project in your docker container.

**Comment by WuzhouDu** [comment]
> Use cmake3 —version instead of cmake —version, and you will get the latest cmake.

Thanks a lot. I think this issue could be closed as your answer has solved it in my environment. 

But could you please correct the project description? Cuz it only says using `cmake --version` to check the cmake version in the docker container, instead of `cmake3 --version`.

**Comment by tonyyxliu** [comment]
OK, I will update the document ASAP. Thanks for pointing out!
