### ISSUE TITLE
Successfully login in terminal, but not vscode SSH remote.

### ISSUE THREAD

**Issue by hansheng-zhang** [tonyyxliu/CUHKSZ-CSC4005#2]
https://github.com/tonyyxliu/CSC4005-2023Fall/assets/85629216/c2023e56-8ec5-445a-ac8f-02955b17d197

According to this video, I can use ssh to login in my terminal. When I use vscode, at first I can load the folder and files on the remote folder. However, later after I see the window "setting SSH host", I cannot connect to the host anymore. Whay could be the problem?

**Comment by tonyyxliu** [comment]
It looks weird to me. You have successfully logined the cluster with SSH. Maybe you could bring your laptop on the tutorial next week so that I can operate on it.

**Comment by hansheng-zhang** [comment]
Thank you!

**Comment by I-am-Future** [comment]
For the first view, I guess if the network is unstable. In my experience, when the network situation is not good, the vscode always losts its connection and reloads window ("shows setting SSH host"). But... I am not sure. Have you tried to login in other places where network may be more stable?

**Comment by hansheng-zhang** [comment]
> For the first view, I guess if the network is unstable. In my experience, when the network situation is not good, the vscode always losts its connection and reloads window ("shows setting SSH host"). But... I am not sure. Have you tried to login in other places where network may be more stable?

Unfortunately, I tried in my dormitary today and failed😭

**Comment by AmyTao** [comment]
I also cannot use ssh to login docker. The error shows like this:
![35691694415498_ pic](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89523120/56ab83e5-61de-4537-927a-955766a2f96b)

**Comment by hansheng-zhang** [comment]
> 

Solution: use terminal and login to the cluster. Delete the whole folder '.vscode-server'. Restart vscode and login ssh again.
