### ISSUE TITLE
project built failure because cuda version 10.2 is unavailable 

### ISSUE THREAD

**Issue by iamgeorge** [tonyyxliu/CUHKSZ-CSC4005#20]
When I try to use cmake to build the project via vscode, it reported an error saying cuda version 10.2 is unavailable.
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/167d44a2-0657-4fb5-8efd-3d361399d65a)
However, when I do nvcc --version, the version is 11.4:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/29336039-7ce8-4796-8cfa-bbfbf50c4733)
How can we solve this issue?

**Comment by xhn2333** [comment]
Can you show more detailed command of compling?

**Comment by tonyyxliu** [comment]
Hi @iamgeorge 

You can add this line to your CMakeLists.txt under src/gpu

`set(CMAKE_CUDA_COMPILER "/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin/nvcc")`

**Comment by iamgeorge** [comment]
> Hi @iamgeorge
> 
> You can add this line to your CMakeLists.txt under src/gpu
> 
> `set(CMAKE_CUDA_COMPILER "/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4/bin/nvcc")`

I have added the line to cMakeList, but the same problem is still occuring.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/e3030e17-b501-4b7f-967a-55374bc71f21)
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/f9f13b11-3fa2-4129-bdc1-413481bf4cb0)

**Comment by tonyyxliu** [comment]
Can you get the correct version (21.7) for `pgc++` in your docker container with the command `pgc++ --version`? It seems that there is still something wrong with your $PATH.

**Comment by iamgeorge** [comment]
> Can you get the correct version (21.7) for `pgc++` in your docker container with the command `pgc++ --version`? It seems that there is still something wrong with your $PATH.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/1165d49e-f78d-4123-b399-47cf141dd9e7)
The pgc++ --version reports 21.7

**Comment by xhn2333** [comment]
please delete the whole `build` folder then re-do the cmake setup steps.

**Comment by iamgeorge** [comment]
> please delete the whole `build` folder then re-do the cmake setup steps.

I have already tried this many times but it is not working

**Comment by KillerPQY** [comment]
I have met the same problem. 
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/77763966/c53b1a71-dfb1-4c6b-a470-f7611f5502f8)
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/77763966/91994611-e388-49c8-b9ed-6f8807125897)
How to solve this?

**Comment by iamgeorge** [comment]
> I have met the same problem.
> ![image](https://user-images.githubusercontent.com/77763966/272199407-c53b1a71-dfb1-4c6b-a470-f7611f5502f8.png)
> ![image](https://user-images.githubusercontent.com/77763966/272199579-91994611-e388-49c8-b9ed-6f8807125897.png)
> How to solve this?

I give up using the docker eventually, I instead installed all packages on my native wsl. It turned out to be just fin
![1541696322672_ pic](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/11155263/ac955b04-d9c9-420f-bcd4-5adfd0aa5274)
e.

**Comment by tonyyxliu** [comment]
Seems that there are still students encountering this problem this year, and I have finally figured out the solution. The solution turns out to be simple, just setting `export CUDA_HOME=/opt/nvidia/hpc_sdk/Linux_x86_64/21.7/cuda/11.4` should fix this issue.
