### ISSUE TITLE
Question about the edge of the graph

### ISSUE THREAD

**Issue by salixc** [tonyyxliu/CUHKSZ-CSC4005#23]
For part B, when we choose different ways to deal with the edge (setting 0 for missed neighbors OR only handling the inner graph), the content of the edge will be slightly different. So, I wonder if these differences influence the final judgment and grade.

For example, the first graph is the result of my code (setting 0 for missed neighbors) and the second one is the result of the sample code of part B (sequential one, only handling the inner graph). We can see that there are only small differences on the edge:

![seq](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/91480774/a1678231-f899-43bf-9891-19fb21e00d49)
![simd](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/91480774/59731889-707d-47eb-b50a-77809ff48381)

**Comment by tonyyxliu** [comment]
Hi @salixc 

Like I wrote in the instruction, both ways are fine, and it will not influence your grade.

**Comment by salixc** [comment]
Thanks!
