### ISSUE TITLE
gcc -v在docker版本不对

### ISSUE THREAD

**Issue by RuiRuihigh** [tonyyxliu/CUHKSZ-CSC4005#24]
# Install cmake3 with yum
yum install cmake3 -y
cmake --version # output should be 3.17.5
# Install gcc/g++-7 with yum
yum install -y centos-release-scl*
yum install -y devtoolset-7-gcc*
scl -l
scl enable devtoolset-7 bash
gcc -v 

在执行完上述指令之后，gcc -v的结果还是4.8并没有变成7

**Comment by tonyyxliu** [comment]
Hi @RuiRuihigh 

You just raised a good question! I have tried in my docker container, and the `scl enable devtoolset-7 bash` can only change the version of gcc for once. You will not access gcc-7 the next time you enter the container. A permanent solution is to add the following path to your `~/.bashrc` file.

```bash
echo "export PATH=/opt/rh/devtoolset-7/root/usr/bin:$PATH" >> ~/.bashrc
source ~/.bashrc
```

Thank you very much for pointing out! I will update the document ASAP.

**Comment by tonyyxliu** [comment]
I have updated this to the document in commit: https://github.com/tonyyxliu/CSC4005-2023Fall/commit/9501a81906bbd7cb506c797b68f80865832c5306. The isseu number is mistaken in the commit message.

Let's close this issue.
