### ISSUE TITLE
Question about GIven Code of Project1 PartA

### ISSUE THREAD

**Issue by WuzhouDu** [tonyyxliu/CUHKSZ-CSC4005#28]
I have difficulty understanding some SIMD Part A code. In the `.../CSC4005- 2023Fall/project1/src/cpu/simd_PartA.cpp` file, 59th and 60th lines of code are below:
```cpp
        // Load the 8 red chars to a 256 bits float register
        __m128i red_chars = _mm_loadu_si128((__m128i*) (reds+i));
```
variable incurred: 
```cpp
auto reds = new unsigned char[input_jpeg.width * input_jpeg.height + 16];
```
So, the code means loading 128 bits from `reds`, i.e. 16 red channel characters each with a 0-255 value, to `red_chars`. That is to say, this line handles 16 pixels of red channels. But why does the 59th comment say it only loads 8 red chars? It also confuses me that the iteration stridence is 8.

Thank you for your kind answer.

**Comment by zihan0822** [comment]
Though it reads 16 bits from the red channel, it only uses the first 8. Because you need to amplify each uchar (8 bits) to float (32 bits) in order to take floating point operation afterwards. This is what `_mm256_cvtepu8_epi32` function does in the next line. A $8\times32 = 256$ bits vector register can only accommodate 8 float.

**Comment by WuzhouDu** [comment]
> Though it reads 16 bits from the red channel, it only uses the first 8. Because you need to amplify each uchar (8 bits) to float (32 bits) in order to take floating point operation afterwards. This is what `_mm256_cvtepu8_epi32` function does in the next line. A 8×32=256 bits vector register can only accommodate 8 float.

Thanks!  I get it. the function `_mm256_cvtepu8_epi32` is used to zero-extend the lower eight unsigned 8-bit integers in a 128-bit integer vector to 32-bit integers in a 256-bit integer vector. The upper eight elements of the input vector are unused.
