### ISSUE TITLE
failed to execute OpenMP partB (Invalid Argument)

### ISSUE THREAD

**Issue by LuoZhexu** [tonyyxliu/CUHKSZ-CSC4005#29]
I didn't change anything in sbatch_PartB.sh and copy all the content in openmp_PartA.cpp into openmp_PartB.cpp (which means they are the same).
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/36c63dc2-fd81-4dc2-8df3-df1392831266)
However, when I submitted sbatch_PartB.sh, it showed that there exists an argument error (I have 4 arguments instead of 3). 
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/8d14b658-9274-4f44-9393-953d9933b6ac)
But things still went well in sbatch_PartA.sh, with all the contents being the same.
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/6620bd6a-466a-4831-99e1-5403a0078473)
And here is the Cmakelist.txt:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/f5d0135d-074c-4663-a85b-0a5dab2d4d6c)

I couldn't figure out why this happen.

**Comment by 58191554** [comment]
Please show the entire instruction for srun in your sbatch. I think the srun you write is not correct. Please follow the first few lines in your cpp code that can give you some hint about the input argvs

**Comment by LuoZhexu** [comment]
This is srun instruction in sbatch.sh. Actually I directly copied this sbatch file from Github and only change the output jpg file's name. 
# OpenMP PartB
echo "OpenMP PartB (Optimized with -O2)"
for num_cores in 1 2 4 8 16 32
do
  echo "Number of cores: $num_cores"
  srun -n 1 --cpus-per-task $num_cores ${CURRENT_DIR}/../../build/src/cpu/openmp_PartB ${CURRENT_DIR}/../../images/20K-RGB.jpg ${CURRENT_DIR}/../../outputs/20K-Smooth5.jpg ${num_cores}
  echo ""
done

**Comment by LuoZhexu** [comment]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/96827c16-c651-4c5f-9ea4-250442b347ca)

**Comment by LuoZhexu** [comment]
When I compared it with sbatch_PartA.sh, it seems that it should not include "${num_cores}". Therefore they may exist some typo in your given sbatch_PartB.sh in Github as shown below.
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/4bd6696a-c01e-4edf-bd80-8e0427e2c503)


![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/115707762/d1f46002-e314-4895-968e-602db3dff07c)

**Comment by tonyyxliu** [comment]
Hi @LuoZhexu 

You have raised a good question. It is our mistake that the OpenMP program for PartA and PartB should be able to manually set the number of cores to launch with the last parameter in the terminal, so the command to execute OpenMP program should always be as follows:
`srun -n 1 --cpus-per-task ${num_cores} /path/to/executable /path/to/20K-RGB.jpg /path/to/20K-Output.jpg ${num_cores}`

**Note:** for PartB, it does not matter where the `${num_cores}` is in the command. It can be the any argument in argv, or simply a flag like `--cores ${num_cores}`.

Please implement in this way for your PartB OpenMP and Pthread program. As for the problem of PartA OpenMP program, we will update it soon and you don't need to worry about it.
