### ISSUE TITLE
cmake problem in docker

### ISSUE THREAD

**Issue by maryhadalittlecode** [tonyyxliu/CUHKSZ-CSC4005#30]
[root@f7a30cda31ca project1]# cmake3 .
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/CSC4005/CSC4005-2023Fall/project1/CMakeFiles/CMakeOutput.log".

Thanks a lot for any help!

**Comment by tonyyxliu** [comment]
Hi @MARYscu 

Try two dots instead of one after the `cmake3`, that is `cmake3 ..`

**Comment by maryhadalittlecode** [comment]
> Hi @MARYscu
> 
> Try two dots instead of one after the `cmake3`, that is `cmake3 ..`

Yeah, I tried that as well. Neither works for me
