### ISSUE TITLE
Could NOT find OpenACC_CXX

### ISSUE THREAD

**Issue by KillerPQY** [tonyyxliu/CUHKSZ-CSC4005#32]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/77763966/8b15752d-bba9-434d-b73b-7fec7a2950b6)

When I use cmake3, this problem will appear, but pgcc -V works well for me, so how to solve this?

**Comment by tonyyxliu** [comment]
I am sorry that I don't know how to fix this issue. It seems that the OpenACC you found with Version 1.0 is not correct. You should find OpenACC with version 2.0. If you are stuck by this problem, please compile your OpenACC program manually with the `pgc++` or `pgcc`. That is completely fine.
