### ISSUE TITLE
How can we know the filtered picture fulfills the requirement?

### ISSUE THREAD

**Issue by RuiRuihigh** [tonyyxliu/CUHKSZ-CSC4005#33]
I found that the results between using int and float are different. If I use int, the filtered picture will be obviously blurred. However, If I use float, the resulting picture will be just like the original picture--cannot be distinguished by direct observation. Thus, I want to know how to judge whether the filtered picture is correct.

**Comment by tonyyxliu** [comment]
It is OK if your output image for PartB with smooth filter (1/9 equal weight) is roughly the same as the original image.

**Comment by tonyyxliu** [comment]
To better test your smooth filter implementation, pelase execute your parallel programs first on the Lena-RGB.jpg, and you should get a vague output as shown in the Project 1 instruction.
