### ISSUE TITLE
Concerns about compilation flags

### ISSUE THREAD

**Issue by EnderturtleOrz** [tonyyxliu/CUHKSZ-CSC4005#34]
When I implemented the code using SIMD, I got the following error when compiling because I used some special functions.
```
error: inlining failed in call to always_inline
```
An easy way to fix this bug is adding a compilation flag "-march=native". Are we allowed to use it?

If possible, could you provide a list of flags that can/cannot be used?

**Comment by tonyyxliu** [comment]
You can use any optimization flag / option you want, but you have to specify them out in the report that, how did these extra optimization work to speedup your program. In your case, please explain why you want to introduce those special functions for SIMD?
