### ISSUE TITLE
A typo in tutorial1 

### ISSUE THREAD

**Issue by yigudove** [tonyyxliu/CUHKSZ-CSC4005#35]
![微信截图_20231006093849](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/a64aa863-0c0c-4c5d-b93e-19500fee04c9)

here 
g++ lpthread ./pthread_vector_addition.cpp -o ./pthread_vector_addition

shoule be 
g++ -lpthread ./pthread_vector_addition.cpp -o ./pthread_vector_addition

![微信截图_20231006094028](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/86c8ad84-79ac-4446-9c21-3e0458230f4c)

**Comment by tonyyxliu** [comment]
Hi @yigudove 

Thank you so much for pointing out this typo as well as helping us answer the questions from other students. I have fixed that typo with a new commit.
