### ISSUE TITLE
Can't find nvcc, no cuda on the cluster

### ISSUE THREAD

**Issue by qxytw** [tonyyxliu/CUHKSZ-CSC4005#36]
I can't compile and run the cuda and openACC version of PartA, and they can't ran at all. I also tried to type nvcc and run stats in my terminal, but it just shows "command not found." There is no cuda on my cluster, strangely. 

CUDA PartA
srun: error: node24: task 0: Exited with exit code 2
slurmstepd: error: execve(): /nfsmnt/120010025/project1/src/scripts/../../build/src/gpu/cuda_PartA: No such file or directory

OpenACC PartA
srun: error: node24: task 0: Exited with exit code 2
slurmstepd: error: execve(): /nfsmnt/120010025/project1/src/scripts/../../build/src/gpu/openacc_PartA: No such file or directory

<img width="1093" alt="image" src="https://github.com/tonyyxliu/CSC4005-2023Fall/assets/35256104/df890a57-5de6-4f89-a359-c18c252393ca">

**Comment by yigudove** [comment]
check the closed issues will be a good behavior :)
https://github.com/tonyyxliu/CSC4005-2023Fall/issues/3
