### ISSUE TITLE
can not find exist complied files when execute sbatch_PartA.sh 

### ISSUE THREAD

**Issue by yigudove** [tonyyxliu/CUHKSZ-CSC4005#37]
I am following tut3 and use "sbatch ./src/scripts/sbatch_PartA.sh" to execute the compiled file.
however it return error in Project1-PartA-Results.txt:
```
Sequential PartA (Optimized with -O2)
slurmstepd: error: execve(): /nfsmnt/120090716/project1/src/scripts/../../build/src/cpu/sequential_PartA: No such file or directory
srun: error: node23: task 0: Exited with exit code 2
```

while I am quite sure /nfsmnt/120090716/project1/src/scripts/../../build/src/cpu/sequential_PartA exists.
![微信图片编辑_20231006225347](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/b65627b9-df26-47b9-8e3f-a8135cd7d540)

**Comment by yigudove** [comment]
I can run them separately and get gray images.
![微信截图_20231007003305](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/1f56dd31-c4be-4b99-a9f3-35f3650581db)

**Comment by 120090162** [comment]
you can try to use the absolute path instead of the relative path

**Comment by yigudove** [comment]
> you can try to use the absolute path instead of the relative path

things seems going well after I use absolute path.
but I still want to know why would this happen. Neither new bing nor chatgpt can give me a reasonable explanation.

```
# the two paths should be the same
[ -f /nfsmnt/120090716/project1/bulid/src/cpu/sequential_PartA ] && echo yes || echo no

[ -f /nfsmnt/120090716/project1/src/scripts/../../build/src/cpu/sequential_PartA ] && echo yes || echo no
```
![微信图片_20231007115930](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/b1780d95-2d63-4880-8abf-aac9e35acab2)

**Comment by xhn2333** [comment]
It seems that there should be some problems with the cluster setup. Slurm server was restarted recently. The problem seems solved.

**Comment by yigudove** [comment]
> It seems that there should be some problems with the cluster setup. Slurm server was restarted recently. The problem seems solved.

The weird thing is that the situation is reversed. Now the absolute path returns no and relative path returns yes which is reversed from before. Anyway, I'm not putting any more time into it.
<img width="747" alt="微信截图_20231010114533" src="https://github.com/tonyyxliu/CSC4005-2023Fall/assets/109584096/e9aebfec-a898-4669-9811-7d515f4c5303">
