### ISSUE TITLE
SIMD for PartB

### ISSUE THREAD

**Issue by Yae-mikooo** [tonyyxliu/CUHKSZ-CSC4005#40]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/118322954/834ba784-6181-4b41-8bea-b17c7145b59e)
I wonder if there is any possible reason cause it. Appreciate any help!

**Comment by MeloYang05** [comment]
It seems that each line has the same color. I think maybe something wrong happens when you store the pixels from the register to the memory?
