### ISSUE TITLE
Should I consider JPEGMeta Struct Here A Bad Pattern in the Context of C++?

### ISSUE THREAD

**Issue by Congyuwang** [tonyyxliu/CUHKSZ-CSC4005#42]
<img width="634" alt="截圖 2023-10-08 19 31 16" src="https://github.com/tonyyxliu/CSC4005-2023Fall/assets/52687642/2d8011ac-cadc-42e4-a39a-96f386af0eb9">

Just to suggest that this JPEGMeta be handled with a class with RAII pattern instead of struct.

So that no manual allocation is needed (done in constructor), and no manual deallocation, plus a reasonable move or copy assignment syntax.

Perhaps this is not the point of this course. But I do think this may be a point of improvement for future students to learn from best & safe practices (in the context of CPP).

**Comment by I-am-Future** [comment]
I agree with you. In context of modern C++ using here, I think it is good to use RAII and other modern C++ features for this struct. 👍

**Comment by tonyyxliu** [comment]
Thanks for pointing out! I will refine this struct for the next semster.

**Comment by MeloYang05** [comment]
Thank you for your comments, and we will strive to adhere to modern C++ conventions in our future projects. In fact, for Assignment2, I have already implemented the modern C++ style. However, for the sake of performance optimization, there are instances where it is preferable to minimize excessive abstractions. As a result, the code structure for Assignment2 does not heavily rely on modern C++ features. Thank you for your understanding.

**Comment by Congyuwang** [comment]
Performance is a good point! [CppCon 2019: Chandler Carruth “There Are No Zero-cost Abstractions”](https://www.youtube.com/watch?v=rHIkrotSwcc&t=1261s) on the cost of `unique_ptr`.
