### ISSUE TITLE
Proj2 - Question about matrix sizes

### ISSUE THREAD

**Issue by salixc** [tonyyxliu/CUHKSZ-CSC4005#47]
I would ask about the sizes of 5 evaluation testcases:

1. Will all of these matrices be square ones (i.e. M = K = N) just like the provided 4 groups of matrices? If not, would extra rectangular matrices be provided for us to test the correctness?

2. Will all values of M, K, N of these matrices be n-th power of 2 (i.e. M / K / N = 2^n )?

Many thanks!

**Comment by tonyyxliu** [comment]
Hi @salixc 

Please refer to issue #46 , which is roughly the same to your question, and TA Yang Yufan gave the following answer:

> You should support any size of matrix as long as the multiplication is legal. Therefore, M, N, K may be not equal.

There is a file to generate matrices in your project, and I think it's easy for you to modify a bit to generate rectangle matrices for you to do testing by yourself. We may not provide testscases for that.
