### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by GuanlinWU123** [tonyyxliu/CUHKSZ-CSC4005#5]
![Screenshot from 2023-09-11 12-32-13](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/76504335/a18be8b2-5bae-4d52-a5d4-c485bf921b1a)
Hi! After downloading the docker container and cuda 12.2, when I run this instruction, it appears this error. Should I install the Nvidia Toolkit as this [link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) illustrates?

**Comment by tonyyxliu** [comment]
Hi @GuanlinWU123 
What is the terminal output of `nvidia-smi`?

**Comment by GuanlinWU123** [comment]
![Screenshot from 2023-09-11 12-59-37](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/76504335/3cadfd28-bb67-4e1d-8ae0-be821775678a)
This one

**Comment by tonyyxliu** [comment]
Sorry that I have no idea for now. I will keep you informed if I have found the solution.

**Comment by GuanlinWU123** [comment]
Hi! I have figured out the solution to this problem, just follow the instruction on this [link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.14.0/install-guide.html). It is just because I didn't install Nvidia Toolkit before to make enable the container has access to CUDA.

**Comment by GuanlinWU123** [comment]
@tonyyxliu I think you can add this comment to the user guide for the installation of docker to make everybody's life easier. My execution screenshot looks like this, 
![Screenshot from 2023-09-11 22-53-47](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/76504335/2ceda6f2-24cc-410b-a4fa-d18861b0016e)

**Comment by tonyyxliu** [comment]
> Hi! I have figured out the solution to this problem, just follow the instruction on this [link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.14.0/install-guide.html). It is just because I didn't install Nvidia Toolkit before to make enable the container has access to CUDA.

Thank you, I will include that in the instruction. It is very helpful!
