### ISSUE TITLE
srun: error: node25: task 11: Killed

### ISSUE THREAD

**Issue by BaoRui666** [tonyyxliu/CUHKSZ-CSC4005#51]
I encounter this problem when testing different bucket number when doing bucket sort. When testing n=100,000,000 and bucket num = 600,000 or 800,000.. It returns this:

srun: error: node25: task 11: Killed
srun: error: node25: task 19: Killed
srun: error: node25: task 9: Killed
srun: error: node25: task 17: Killed
srun: error: node25: task 5: Killed
srun: error: node25: task 23: Killed
srun: error: node25: task 15: Killed
srun: error: node25: task 1: Killed
srun: error: node25: task 21: Killed
srun: error: node25: task 29: Killed
srun: error: node25: task 14: Killed

What could be the possible reason? I have checked smaller n and bucket number, it runs normally.

**Comment by MeloYang05** [comment]
Hello! The reason that your running time is too long so that your task is killed. My suggestion is that you could test your program locally to ensure that its performance is close to the baseline, then all the tests with srun could be finished in time
