### ISSUE TITLE
Baseline Concern about Project3-Task3

### ISSUE THREAD

**Issue by I-am-Future** [tonyyxliu/CUHKSZ-CSC4005#52]
Hi TAs,
    I found that the given Project3-Task3's baseline for 1 worker is ~37000ms. But I found that I tried many many times, running the pure sequential code is ~42000ms. My odd-even sort implementation for 1 worker is also around ~41000-42000ms. Why the 1 worker baseline could be significantly faster than sequential? No matter there are additional overheads? Can you please give me some improvement hints? Thank you!

**Comment by MeloYang05** [comment]
Hello! I think 41000-42000ms is acceptable, don't be too worry. I think when I conduct the experiment, the machine is relatively free, so the performance will be a little bit better.

**Comment by I-am-Future** [comment]
Yeah, I found that may be the problem. I ran it today 1 a.m., speed is about 39000-40000ms.... But I am not sure whether a in-node  communication would be affected significantly? because I think when I am running the program, one node is all assigned to me?

**Comment by MeloYang05** [comment]
> Yeah, I found that may be the problem. I ran it today 1 a.m., speed is about 39000-40000ms.... But I am not sure whether a in-node communication would be affected significantly? because I think when I am running the program, one node is all assigned to me?

I am not sure, @tonyyxliu may be more familiar with the cluster. In my optinion, I believe there are some load distribution machanism of the cluster.
