### ISSUE TITLE
Typo in the document

### ISSUE THREAD

**Issue by hey-money** [tonyyxliu/CUHKSZ-CSC4005#53]
There is a typo in the hints of the even-odd sort section:

> For example, let's assume the complete array is [1, 2, 4, 3, 5, 6], and there are two processes. Process 1 gets [1, 2, 3], and process 2 gets [4, 5, 6].

should be 

> For example, let's assume the complete array is [1, 2, 4, 3, 5, 6], and there are two processes. Process 1 gets [1, 2, 4], and process 2 gets [3, 5, 6].

**Comment by tonyyxliu** [comment]
You are right, and thanks for pointing out! I have fixed this typo in the commit mentioned here.
