### ISSUE TITLE
What is the difference between loss and error

### ISSUE THREAD

**Issue by SummerSunnyNight** [tonyyxliu/CUHKSZ-CSC4005#56]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/3236e88b-4913-468e-aff5-c947575578a9)
I know that the loss is calculated by this function:
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/54a1baee-b9f5-4779-a17e-fb2f936f3b53)

What about the error?
Thanks

**Comment by 120090162** [comment]
An error means that the classification result calculated by the model is different from the real result. So Err can be calculated by 
(The sum of Err / total image number).
