### ISSUE TITLE
How should I set the initial value for theta in softmax regression?

### ISSUE THREAD

**Issue by Yae-mikooo** [tonyyxliu/CUHKSZ-CSC4005#57]
The baseline notice required me that the outcome should be the same as the sample outcome number by number.

**Comment by xhn2333** [comment]
Please use the given random method in sequential sample.

**Comment by Yae-mikooo** [comment]
if my results in nn part are slightly smaller than the sample outcome, e.g. 0.05862/0.05819, which may cause by the randomly initial W, does it matter?
