### ISSUE TITLE
[Proj 4] About the profiling

### ISSUE THREAD

**Issue by salixc** [tonyyxliu/CUHKSZ-CSC4005#59]
According to the requirements of the project, I used "perf record" and "nsys" to profile the programs. However, the recording data files of NN are quite large (429MB for sequential and 108MB for OpenACC), which may be inconvenient to submit and download. So, I would like to ask if we should submit them directly or if there are any other methods available. Thanks.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/91480774/1299d266-d7bc-4f93-b0f8-c02ba8abdf43)

Here are the commands I used:
perf record -e cpu-cycles,cache-misses,page-faults -g -o ./xxx
nsys profile -t cuda,nvtx,osrt,openacc -o ./xxx

**Comment by tonyyxliu** [comment]
If the profiling file is too large, then it is a better way to submit summarized information with `perf stat` and `nsys`. As for the .qdrep file, if you have installed Nsight System, you can include the screenshot in the software for a proof that you have done the profiling.

Please do not directly submit such large files on BB, and thank you for your understanding!
