### ISSUE TITLE
Unable to connect docker via SSH

### ISSUE THREAD

**Issue by AmyTao** [tonyyxliu/CUHKSZ-CSC4005#6]
Hi there!
I have completed steps to use ssh connecting docker container in the manual until `/usr/sbin/sshd -D.`
Then came an error like this:
![35691694415498_ pic](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89523120/98271b42-0c7e-4fa8-a486-d47705e925ba)

Anyone can solve this problem?
I have tried to modify the sshd_config with 
```
PubkeyAuthentication = yes
AllowRootLogin = yes
Port = 22
```
but the error still exists.

**Comment by tonyyxliu** [comment]
In the screenshot, you used `service ssh start` instead of `/usr/sbin/sshd -D`. Even if you want to use service, you may need to start sshd service instead of ssh service. So please try the three commands:

`/usr/sbin/sshd -D`
or
`service sshd restart`
or
`systemctl sshd restart`

I succeeded with the first command in the container yesterday.

**Comment by AmyTao** [comment]
I have tried to use the compressed package in the cluster. I use `systemctl start ssh` to start ssh because it shows `bash: service: command not found` when I try to use `service`. However, the result is the same.
When I try to login through SSH, another error window shows:
![35711694424436_ pic](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89523120/26f06cf9-0632-4329-8333-ac87cb924139)

**Comment by AmyTao** [comment]
I delete known_hosts inside .ssh and the errors change like this:
![35721694425517_ pic](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/89523120/ffe2d211-67c7-4188-b237-f36161924181)
I wonder whether I should did 
```
ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ''
ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key -N ''
``` 
inside container or on my local environment.

**Comment by Eightina** [comment]
container

**Comment by 58191554** [comment]
At the first time you the image doesn't have a host key, and you need to generate it.
`[root@2dc2da7a1e5e /]# /usr/sbin/sshd
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key`

Then, generate it 
`[root@2dc2da7a1e5e ssh]# ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:dWFGPhfBt7QK78K0u4D1P4uuVy1d9RgxMmFcfkKr9Ek root@2dc2da7a1e5e
The key's randomart image is:
...`

Give correct authentication: chmod 600 /etc/ssh/ssh_host_*
You will be ok after that folloing the doc by TAs
