### ISSUE TITLE
Bad file descriptor when git clone or git pull

### ISSUE THREAD

**Issue by tonyyxliu** [tonyyxliu/CUHKSZ-CSC4005#67]
Seems to be issues of NFS

![1726562544920](https://github.com/user-attachments/assets/606c7fb1-3ba1-4f01-b684-658673b4d9ef)

**Comment by Maxorao** [comment]
I found the same problem on the cluster, could you help me to fix it up? or provide another way to get the files of project 1

**Comment by tonyyxliu** [comment]
I think everything should be fine after re-mounting the NFS directory with ver4.0 in the client side.
