### ISSUE TITLE
Failed to pass sample program 5(CUDA)

### ISSUE THREAD

**Issue by I-am-Future** [tonyyxliu/CUHKSZ-CSC4005#7]
I met a problem when running the sample program.

**What I did**:
1. clone this repo, and `cd` to the "sample_directory" folder.
2. execute the command in README one by one.

**What problem I met**:
1. After I write `srun -n 4 ./cuda_hello`, there are nothing displayed in the terminal (No "Hello, World! from thread xxx" shown). 

Then, I tried to get the error by the following code:
```cuda
    cudaError_t err = cudaDeviceSynchronize();
    printf("after launch\n");
    printf("error: %d\n", err);
    printf("error string: %s\n", cudaGetErrorString(err));
```
The result becomes:
>$ ./cuda_hello 
main thread cuda_hello.cu 10
after launch
error: 35
error string: CUDA driver version is insufficient for CUDA runtime version

Therefore, I guess if there are some problem with the driver. the `nvcc -V` result is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```
and `nvidia-smi` results in `bash: nvidia-smi: command not found...`

So, I guess, if there are problem with CUDA version? I guess if the compiler's cuda version is higher than the cuda driver runtime. (PS: the allocated node is node01)

Thank you!

**Comment by tonyyxliu** [comment]
You are right. CUDA and OpenACC have not been fully configured on the cluster, since we need to uninstall CUDA and install NVIDIA HPC SDK. Please wait until further announcement. I am sorry for that.

**Comment by tonyyxliu** [comment]
`nvidia-smi` command not found is because I uninstalled the NVIDIA driver on the cluster a few days ago. I will install a new one this evening.

**Comment by I-am-Future** [comment]
Hey dear TA, I think you don't need to say sorry. I totally understand that configuring the cluster well is a really hard work. In some cases, the problem may be tooooo difficult to figure out. I'll wait for the updates. I really appreciate your work to enable us experience in the world's first-class computer science courses. Again, thank you for your hard work!

**Comment by tonyyxliu** [comment]
Thank you for your kindness! I have installed CUDA and NVIDIA HPC SDK on every node on the cluster. CUDA programs should be executed as expected.

**Comment by tonyyxliu** [comment]
```bash
[root@node21 sample_programs]# salloc -N1 -n4 -t5 -pDebug
salloc: Granted job allocation 88173
salloc: Waiting for resource configuration
salloc: Nodes node01 are ready for job
[root@node21 sample_programs]# srun -n 4 ./cuda_hello
Hello, World! from thread 0 of block 0
Hello, World! from thread 1 of block 0
Hello, World! from thread 0 of block 0
Hello, World! from thread 1 of block 0
Hello, World! from thread 0 of block 0
Hello, World! from thread 1 of block 0
Hello, World! from thread 0 of block 0
Hello, World! from thread 1 of block 0
```
