### ISSUE TITLE
Potential error in grading policy

### ISSUE THREAD

**Issue by LouisCroix** [tonyyxliu/CUHKSZ-CSC4005#73]
In the grading policy for Project 1, it says we need to include "What kinds of optimizations have you tried to speed up your parallel program for PartB, and how do them work?" in our report. Should "PartB" here be "PartC", since we do not need to implement programs for PartB?

**Comment by LouisCroix** [comment]
What's more, an instruction under the subtitle PartB (Baseline Performance) that says "If your program can achieve similar performance to the baseline shown below, you can get the full mark for your performance part, which weights for 30%" should this instruction be omitted? I doubt that these weird instructions for part B are all instructions left from previous semesters, since we do not need to implement the code for Parts A and B.

**Comment by tonyyxliu** [comment]
Yes, you are right that we did not update the documents carefully. PartB was the job last year, but this year, you only need to handle PartC.
