### ISSUE TITLE
Compiling error caused by adding SIMD code to utils.py

### ISSUE THREAD

**Issue by LouisCroix** [tonyyxliu/CUHKSZ-CSC4005#74]
I've encountered a weird issue when implementing a bilateral filter function using SIMD in utils.py. When compiling, an error is raised with the following information:
![image](https://github.com/user-attachments/assets/0979324c-4892-44a3-bf49-1dd71a99680d)

If any further information is needed, please tell me. I would appreciate it if you could solve this problem for me.

**Comment by tonyyxliu** [comment]
It sounds weird to me too. Please make sure you attach the right compiler option like `-mavx2`.
