### ISSUE TITLE
Failed to pass sample program 6(OpenACC)

### ISSUE THREAD

**Issue by I-am-Future** [tonyyxliu/CUHKSZ-CSC4005#8]
I also met another problem when running the sample program.

**What I did**:
1. clone this repo, and `cd` to the "sample_directory" folder.
2. execute the command in README one by one.

**What problem I met**:

1. After compile openacc by `pgc++ -acc -mp openacc_parallel.cpp -o openacc_parallel` 
2. I ran `srun -n 4 ./openacc_parallel`, it directly shows error message:

> $ srun -n 4 ./openacc_parallel
/nfsmnt/my-id/CSC4005-2023Fall/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
/nfsmnt/my-id/CSC4005-2023Fall/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
/nfsmnt/my-id/CSC4005-2023Fall/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
/nfsmnt/my-id/CSC4005-2023Fall/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
srun: error: node01: tasks 0-3: Exited with exit code 127

I guess if the libacchost.so is not at the path. I used `ldd openacc_parallel` to check:

> $ ldd openacc_parallel
        linux-vdso.so.1 =>  (0x00007ffde2fba000)
        libacchost.so => /opt/nvidia/hpc_sdk/Linux_x86_64/23.7/compilers/lib/libacchost.so (0x00007f3ebd54d000)
        ......

And I checked, "/opt/nvidia/hpc_sdk/Linux_x86_64/23.7/compilers/lib/libacchost.so" exists. 

In addition, I tried directly call `./openacc_parallel`. It works successfully!

Thank you!

**Comment by tonyyxliu** [comment]
I am sorry. OpenACC has not been installed on other machines of the cluster. As discussed in [issue 7 posted by you](https://github.com/tonyyxliu/CSC4005-2023Fall/issues/7), I will fix that this evening.

**Comment by I-am-Future** [comment]
Hey dear TA, no sorry. I'll wait for the updates. I really appreciate your work for this courses. You are the most serious TA I had seen here. Thank you for your hard work!

**Comment by tonyyxliu** [comment]
Thank you! I am glad to hear that. I have installed NVIDIA HPC SDK, which includes OpenACC on each node on the cluster. However, OpenACC programs seem still in trouble when executed with `srun`

```bash
[root@node21 sample_programs]# srun -n 2 ./openacc_parallel
/nfsmnt/admin/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
/nfsmnt/admin/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
srun: error: node01: tasks 0-1: Exited with exit code 127
```

I am not faimiliar with OpenACC, and I will spend time working on it.

**Comment by tonyyxliu** [comment]
> Thank you! I am glad to hear that. I have installed NVIDIA HPC SDK, which includes OpenACC on each node on the cluster. However, OpenACC programs seem still in trouble when executed with `srun`
> 
> ```shell
> [root@node21 sample_programs]# srun -n 2 ./openacc_parallel
> /nfsmnt/admin/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
> /nfsmnt/admin/sample_programs/./openacc_parallel: error while loading shared libraries: libacchost.so: cannot open shared object file: No such file or directory
> srun: error: node01: tasks 0-1: Exited with exit code 127
> ```
> 
> I am not faimiliar with OpenACC, and I will spend time working on it.

The error is due to I forgot to re-compile the program after the new version of NVIDIA HPC SDK was installed. Now, the programs can be executed in parallel as expected.

```bash
[root@node21 sample_programs]# salloc -N1 -n4 -t5 -pDebug
salloc: Granted job allocation 88173
salloc: Waiting for resource configuration
salloc: Nodes node01 are ready for job
[root@node21 sample_programs]# srun -n 4 ./openacc_parallel
Reduction sum: 1.2020569031119110
Reduction sum: 1.2020569031119110
Reduction sum: 1.2020569031119110
Reduction sum: 1.2020569031119110
```
